spring:
  datasource:
    url: jdbc:mysql://39.99.175.195:3306/zkwg?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


#扫描mapper文件 + 输出SQL日志
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义属性配置
zkwg:
  redis:
    host: 47.92.157.246
    port: 6379
    #没有密码的话 这里留空即可
    pass:
    #连接池最大连接数
    maxTotal: 150
    #最小空闲连接数
    maxIdle: 10
  aes:
    passkey: dP0ykNOnMdKFaXCIOnXckg==